version: 2
machine:
  services:
    - docker
deployment:
  dockerhub:
    branch: master
    commands:
      - $DOCKER_HUB_BUILD_IMAGE_TRIGGER

jobs:
  build:
    working_directory: /temp
    docker:
      - image: microsoft/dotnet:sdk
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build

      